@base = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoiY29ycmVvQGNvcnJlby5jb20iLCJub21icmUiOiJEYW5pZWwgVG9ybyIsImlhdCI6MTc4MDE4NDE3NiwiZXhwIjoxNzgwMjcwNTc2fQ.FJeRTe0H96TfuHi7cZAMvLO-piyJA2iBMD3TjhcXy9I


### Ver todos los usuarios
GET http://localhost:3000/api/auth/usuarios
Authorization: Bearer {{token}}

###

### Eliminar usuario
DELETE {{base}}/api/auth/usuarios/1
Authorization: Bearer {{token}}

###

### Registrar residuo
POST http://localhost:3000/api/residuos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "tipo_residuo": "",
    "cantidad": ,
    "unidad": "",
    "fecha": "aaaa-mm-dd",
    "descripcion": ""
}

###

### Ver todos los residuos
GET http://localhost:3000/api/residuos
Authorization: Bearer {{token}}



###

### Eliminar residuo
DELETE http://localhost:3000/api/residuos/1
Authorization: Bearer {{token}}

### Estadísticas resumen
GET http://localhost:3000/api/estadisticas/resumen

###


